# -*- coding: utf-8 -*-
"""ANN_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GOrtpgdmwkNNwQAJL2kS70e81j615p51
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

url = "https://raw.githubusercontent.com/swarj/MLAssignment2/main/slump_test%20(1).csv"
df = pd.read_csv(url)


#Preprocess the Data
toDrop = ['No']
df = df.drop(toDrop, axis = 1)
df = df.dropna(axis=1)
norm_df = (df-df.mean())/df.std()
norm_df.style

## Train Evaluate